$ python examples/python/stack_trace.py
Traceback (most recent call last):
  File "examples/python/stack_trace.py", line 11, in <module>
    g()
  File "examples/python/stack_trace.py", line 4, in g
    f()
  File "examples/python/stack_trace.py", line 7, in f
    raise Exception("hi")
Exception: hi

---------------------
Traceback (most recent call last):
  File "examples/python/stack_trace.py", line 19, in <module>
    g()
  File "examples/python/stack_trace.py", line 4, in g
    f()
  File "examples/python/stack_trace.py", line 7, in f
    raise Exception("hi")
Exception: hi